openapi: 3.0.3
info:
  title: lumio
  version: 1.0.0
  description: tasks managemnt app
paths:
  /tasks/:
    get:
      operationId: root_retrieve
      description: Returns a list of Task model instances.
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Tasks'
          description: ''
    post:
      operationId: root_create
      description: Creates a new post by authenticated user
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Tasks'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Tasks'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Tasks'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Tasks'
          description: ''
  /tasks/{task_ids}/:
    delete:
      operationId: root_destroy
      description: Deletes multiple Task model instances.
      parameters:
      - in: path
        name: task_ids
        schema:
          type: string
          pattern: ^([0-9a-f-]+,?)+$
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '204':
          description: No response body
  /tasks/{task_id}:
    get:
      operationId: root_retrieve_2
      description: Returns a single Task model instance.
      parameters:
      - in: path
        name: task_id
        schema:
          type: string
          format: uuid
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Tasks'
          description: ''
    patch:
      operationId: root_partial_update
      description: Updates a single Task model instance.
      parameters:
      - in: path
        name: task_id
        schema:
          type: string
          format: uuid
        required: true
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedTasks'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedTasks'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedTasks'
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Tasks'
          description: ''
    delete:
      operationId: root_destroy_2
      description: Deletes a single Task model instance.
      parameters:
      - in: path
        name: task_id
        schema:
          type: string
          format: uuid
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '204':
          description: No response body
components:
  schemas:
    PatchedTasks:
      type: object
      properties:
        id:
          type: string
          format: uuid
          readOnly: true
        title:
          type: string
          maxLength: 100
        description:
          type: string
          nullable: true
        note:
          type: string
          nullable: true
        status:
          type: string
          maxLength: 100
        priority:
          type: string
          nullable: true
          maxLength: 100
        label:
          type: string
          nullable: true
          maxLength: 100
        due_date:
          type: string
          format: date-time
          nullable: true
        minutes_spent:
          type: integer
          maximum: 9223372036854775807
          minimum: -9223372036854775808
          format: int64
          nullable: true
        position:
          type: integer
          maximum: 9223372036854775807
          minimum: -9223372036854775808
          format: int64
        created_at:
          type: string
          format: date-time
          readOnly: true
        modified_at:
          type: string
          format: date-time
          readOnly: true
    Tasks:
      type: object
      properties:
        id:
          type: string
          format: uuid
          readOnly: true
        title:
          type: string
          maxLength: 100
        description:
          type: string
          nullable: true
        note:
          type: string
          nullable: true
        status:
          type: string
          maxLength: 100
        priority:
          type: string
          nullable: true
          maxLength: 100
        label:
          type: string
          nullable: true
          maxLength: 100
        due_date:
          type: string
          format: date-time
          nullable: true
        minutes_spent:
          type: integer
          maximum: 9223372036854775807
          minimum: -9223372036854775808
          format: int64
          nullable: true
        position:
          type: integer
          maximum: 9223372036854775807
          minimum: -9223372036854775808
          format: int64
        created_at:
          type: string
          format: date-time
          readOnly: true
        modified_at:
          type: string
          format: date-time
          readOnly: true
      required:
      - created_at
      - id
      - modified_at
      - title
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
    cookieAuth:
      type: apiKey
      in: cookie
      name: sessionid
