# Generated by Django 5.1.4 on 2025-08-10 17:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0004_label_remove_task_label_task_labels"),
    ]

    operations = [
        migrations.AlterField(
            model_name="label",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
