# Generated by Django 5.1.4 on 2025-08-25 18:12

from django.db import migrations


def create_default_labels(apps, schema_editor):
    """Create default labels"""
    Label = apps.get_model('tasks', 'Label')

    default_labels = [
        {"name": "Personal", "color": "#6366F1"},
        {"name": "Work", "color": "#EF4444"},
        {"name": "Shopping", "color": "#10B981"},
        {"name": "Others", "color": "#F59E0B"},
    ]

    for label_data in default_labels:
        Label.objects.get_or_create(
            name=label_data["name"],
            defaults={
                'color': label_data["color"],
            }
        )


def reverse_create_default_labels(apps, schema_editor):
    """Remove default labels"""
    Label = apps.get_model('tasks', 'Label')

    default_label_names = ["Personal", "Work", "Shopping", "Others"]
    Label.objects.filter(name__in=default_label_names).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0005_alter_label_id"),
    ]

    operations = [
        migrations.RunPython(
            create_default_labels,
            reverse_create_default_labels,
        ),
    ]
